In [14]:
from sklearn.datasets import make_classification
import pandas as pd
import numpy as np

In [27]:
X, y =  make_classification(
    n_samples=500, # 4000 observations
    n_features=6, # 6 total features
    # n_informative=3, # 3 'useful' features
    n_classes=2, # number of classes
)

In [28]:
X

array([[ 1.35017933,  0.40068276, -0.0569208 , -0.37889038, -1.00689493,
         1.34254012],
       [-0.54131055, -0.00385433, -0.21452071,  1.23447003,  0.9250652 ,
        -0.71511331],
       [ 0.95887786, -0.19894771,  0.02427466,  1.26693346,  0.51691802,
        -0.67962041],
       ...,
       [ 0.72822004,  0.52441799, -0.67900454,  2.43739892,  1.25507993,
        -0.21658361],
       [-0.63099409,  0.21482858, -0.42724202, -1.41041714,  1.14869281,
        -0.57549301],
       [-0.76975865,  0.73163116, -0.70566486,  0.41456504,  0.7225475 ,
         0.48677589]])

In [29]:
y

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,

In [30]:
data = np.column_stack((X, y))

In [31]:
data

array([[ 1.35017933,  0.40068276, -0.0569208 , ..., -1.00689493,
         1.34254012,  0.        ],
       [-0.54131055, -0.00385433, -0.21452071, ...,  0.9250652 ,
        -0.71511331,  1.        ],
       [ 0.95887786, -0.19894771,  0.02427466, ...,  0.51691802,
        -0.67962041,  1.        ],
       ...,
       [ 0.72822004,  0.52441799, -0.67900454, ...,  1.25507993,
        -0.21658361,  1.        ],
       [-0.63099409,  0.21482858, -0.42724202, ...,  1.14869281,
        -0.57549301,  1.        ],
       [-0.76975865,  0.73163116, -0.70566486, ...,  0.7225475 ,
         0.48677589,  1.        ]])

In [32]:
pd.DataFrame(data).to_csv("data/random_generated_binary_500_new_data.csv")