In [1]:
from sklearn.datasets import make_classification
import pandas as pd
import numpy as np

In [2]:
X, y =  make_classification(
    n_samples=200000, # 4000 observations
    n_features=6, # 6 total features
    n_informative=3, # 3 'useful' features
    n_classes=2, # number of classes
    weights=[0.5, 0.5]
)

In [3]:
X

array([[-0.29112073,  0.10388688,  1.61101415, -1.23402114,  1.81695383,
        -0.73473104],
       [ 2.63466515, -1.16144651,  0.87547722, -1.29215092, -0.15103483,
        -2.07291419],
       [ 2.71314072, -1.00646828, -1.62915577,  1.42717566, -0.93220231,
        -0.55645312],
       ...,
       [-0.48172188, -0.49631722, -0.71921485,  1.30306417,  1.45243553,
        -0.3835755 ],
       [-0.17727091,  0.56924461, -0.91512496,  0.8323919 , -0.96214601,
         1.29868489],
       [ 0.2149179 , -1.25264947, -0.94958781,  0.70845656, -0.57402452,
        -1.26013634]])

In [4]:
y

array([0, 0, 1, ..., 1, 1, 1])

In [5]:
data = np.column_stack((X, y))

array([[-0.68762401, -0.72067443, -0.45914328, ..., -1.18411808,
        -0.6740097 ,  0.        ],
       [-2.11630616,  0.43970214, -1.35694139, ..., -0.96619648,
        -0.39140879,  0.        ],
       [-0.33037647,  0.23066039,  0.8885326 , ...,  1.83252184,
         0.90660573,  1.        ],
       ...,
       [-0.33728169, -0.77787983, -2.56646057, ...,  0.54412229,
         0.13861853,  1.        ],
       [-1.00233132, -0.064507  ,  0.45971969, ..., -1.9840541 ,
        -0.95299712,  0.        ],
       [ 0.19699219, -0.99044148, -0.07691176, ..., -0.52457357,
        -0.40213916,  0.        ]])

In [6]:
pd.DataFrame(data).to_csv("data/random_generated_balanced_data.csv")