In [1]:
from sklearn.datasets import make_classification
import pandas as pd
import numpy as np

In [8]:
X, y =  make_classification(
    n_samples=200000, # 4000 observations
    n_features=6, # 6 total features
    n_informative=3, # 3 'useful' features
    n_classes=2, # number of classes
    flip_y = 0.2
)

In [9]:
X

array([[ 1.52215063, -0.03571042,  2.12611324, -1.99976919,  1.11625725,
        -2.21616407],
       [ 0.06662281, -1.20833859, -1.24886362, -0.31009579, -1.34149196,
        -0.40101195],
       [-1.47862918,  3.15611155,  2.68210003,  1.51706455,  2.26475798,
         0.81208903],
       ...,
       [ 1.4479523 , -0.44119894,  0.79735294, -0.59768878,  0.74220264,
        -0.92377979],
       [-1.00505284,  1.48968917,  0.45442644,  0.25190657,  0.90794536,
         1.45275603],
       [-0.66602329,  0.89136081,  0.6380525 ,  0.8608875 ,  0.40541159,
         0.19957223]])

In [10]:
y

array([0, 1, 1, ..., 0, 0, 0])

In [11]:
data = np.column_stack((X, y))

array([[-0.68762401, -0.72067443, -0.45914328, ..., -1.18411808,
        -0.6740097 ,  0.        ],
       [-2.11630616,  0.43970214, -1.35694139, ..., -0.96619648,
        -0.39140879,  0.        ],
       [-0.33037647,  0.23066039,  0.8885326 , ...,  1.83252184,
         0.90660573,  1.        ],
       ...,
       [-0.33728169, -0.77787983, -2.56646057, ...,  0.54412229,
         0.13861853,  1.        ],
       [-1.00233132, -0.064507  ,  0.45971969, ..., -1.9840541 ,
        -0.95299712,  0.        ],
       [ 0.19699219, -0.99044148, -0.07691176, ..., -0.52457357,
        -0.40213916,  0.        ]])

In [12]:
pd.DataFrame(data).to_csv("data/random_generated_binary_200000_noisy_data.csv")